### ISSUE TITLE
uct公式

### ISSUE THREAD

**Issue by acvrp-lab** [THUcqb/Connect-Four#1]
@THUcqb
你好！

根据我在网上阅读的其他uct算法的资料，board。cpp 227行的负号可能是多余的吧。。
不过c是自定义的，而且公式对胜负的影响没法直接判断

另外我对readme中提到的uct伪代码某些步骤（99、115、127行）也持怀疑态度，虽然它跟我搜索到的另一份资料是差不多的
http://blog.csdn.net/u014397729/article/details/27366363
能否告知这是什么课程，使用的什么教材，readme提到的讲义pdf能否提供一份，azurebld@qq.com，谢谢！

**Comment by qibinc** [comment]
@azurebld 
你好！

很乐意回答你的几个问题：
1. 的确，信心上限公式中，信心上限值为 “目前回报均值”+“偏移序列”。但程序里记录的Value总是对应与当前节点的回报，由于子结点对应于对手的决策，所以子结点收益越大，对当前节点就越不利。在227行中 Q 之前就有负号。伪代码中向上的更新（Δ=-Δ）也是同样问题。
2. 清华大学计算机系人工智能导论课，教材就是讲义，讲义已上传~

万万没想到人智课的大作业会被翻出来😂
